name: auto-update-software-map
on:
  push:
    branches:
     - main
     - mcobb/auto-update
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: the-capable-hub-aws-ci
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Install Github CLI
        shell: bash
        run: |
          type -p yum-config-manager >/dev/null || sudo yum install yum-utils
          sudo yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          sudo yum -y install gh

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: "software-map"

      - name: Checkout Auto Updater
        uses: actions/checkout@v4
        with:
          repository: "The-Capable-Hub/auto-update-software-map"
          fetch-depth: 1
          path: "auto-updater"

      - name: Setup environment
        shell: bash
        working-directory: ./auto-updater
        run: |
          # Set global env vars:
          export RUN_ID="${{ github.run_id }}_${{ github.run_attempt }}"
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_ENV

          export OUTPUT_DIR="${{ github.workspace }}/${RUN_ID}"
          echo "OUTPUT_DIR=${OUTPUT_DIR}" >> $GITHUB_ENV
          
          #export OUTPUT_LOGS_DIR="${OUTPUT_DIR}/logs"
          #echo "OUTPUT_LOGS_DIR=${OUTPUT_LOGS_DIR}" >> $GITHUB_ENV
          
          export FAILURES_FILE="${OUTPUT_DIR}/failures.txt"
          echo "FAILURES_FILE=${FAILURES_FILE}" >> $GITHUB_ENV

          export SUMMARY_FILE="${OUTPUT_DIR}/summary.md"
          echo "SUMMARY_FILE=${SUMMARY_FILE}" >> $GITHUB_ENV

          export BASE_BRANCH_NAME="mcobb/auto-update"
          echo "BASE_BRANCH_NAME=${BASE_BRANCH_NAME}" >> $GITHUB_ENV

          # Create a unique branch name for this run
          TARGET_BRANCH_NAME="auto-updater/${RUN_ID}"
          echo "TARGET_BRANCH_NAME=$TARGET_BRANCH_NAME" >> $GITHUB_ENV

          # Set up workspace
          mkdir -p ${OUTPUT_DIR}
          #mkdir -p ${OUTPUT_LOGS_DIR}
          touch "${FAILURES_FILE}"

      - name: Setup Auto Updater
        shell: bash
        working-directory: ./auto-updater
        run: |
          # Create python3 venv and install requirements:
          python3 -m venv ./venv
          . ./venv/bin/activate
          python3 -m pip install -r requirements.txt


      - name: Run Auto Updater
        shell: bash
        working-directory: ./auto-updater
        run: |
          . ./venv/bin/activate

          # Create file to contain output from auto-updater (for use in PR body)
          #export OUTPUT_FILE="${OUTPUT_DIR}/auto-update.out"
          #echo "OUTPUT_FILE=${OUTPUT_FILE}" >> $GITHUB_ENV
          #echo "OUTPUT_FILE=${OUTPUT_FILE}"

          # Run auto-updater
          set +e # Don't exit on failure
          for input_yaml in ${GITHUB_WORKSPACE}/software-map/*.yaml; do
            filename="$(basename "${input_yaml}")"

            echo "::group::Processing '${filename}'"

            log_file="${OUTPUT_DIR}/${filename}.log"

            ./main.py ${input_yaml} --output-summary ${SUMMARY_FILE} 2>&1 | tee "${log_file}"
            exit_code=${PIPESTATUS[0]}

            if [ $exit_code -ne 0 ]; then
              echo "FAILED: ${input_yaml} (exit code ${exit_code})"
              echo "${input_yaml}|${exit_code}|${log_file}" >> "${FAILURES_FILE}"
            else
              echo "SUCCESS: ${filename}"

            fi
            echo "::endgroup::"
          done
          set -e

      - name: Determine if there are changes
        id: determine_changes
        shell: bash
        working-directory: ./software-map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n $(git status -s -uall) ]]; then
            echo "Auto updater modified files. A PR will be created..."
            echo "CREATE_PR=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: ${{ steps.determine_changes.outputs.CREATE_PR == 'true' }}
        shell: bash
        working-directory: ./software-map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER_NAME: "github-actions[bot]"
          GIT_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |

          # Set up git
          git config user.name ${GIT_USER_NAME}
          git config user.email ${GIT_USER_EMAIL}

          echo "Pushing to branch: '${TARGET_BRANCH_NAME}'..."

          # Create PR branch
          git checkout -b ${TARGET_BRANCH_NAME}
          git add *.yaml
          git commit -m "Auto update software map"
          git push --set-upstream origin ${TARGET_BRANCH_NAME}

      - name: Create PR
        if: ${{ steps.determine_changes.outputs.CREATE_PR == 'true' }}
        shell: bash
        working-directory: ./software-map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create the PR
          #export OUTPUT_FILE="${OUTPUT_DIR}/full_summary.md"
          if [ -s "${FAILURES_FILE}" ]; then
            echo "# Files which failed to process:"
            while IFS="|" read -r input_yaml exit_code log_file; do
              echo ""
              echo "========================================"
              echo "FAILED: ${input_yaml}"
              echo "Exit code: ${exit_code}"
              echo "========================================"

              cat "${log_file}"

            done < "${FAILURES_FILE}" >> "${SUMMARY_FILE}"
          fi

          echo "Creating PR to merge branch '${TARGET_BRANCH_NAME}' into '${BASE_BRANCH_NAME}'..."
          echo "PR will contain the message body:"
          cat ${SUMMARY_FILE}
          echo ""
          echo ""
          gh pr create \
            --title "Auto update software map" \
            --body-file ${SUMMARY_FILE} \
            --base ${BASE_BRANCH_NAME} \
            --head ${TARGET_BRANCH_NAME}

      - name: Cleanup
        if: always()
        shell: bash
        run: |
          rm -rf "${OUTPUT_DIR}"
