name: auto-update-software-map
on:
  push:
    branches:
     - main
     - mcobb/auto-update
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: the-capable-hub-aws-ci
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Install Github CLI
        shell: bash
        run: |
          type -p yum-config-manager >/dev/null || sudo yum install yum-utils
          sudo yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          sudo yum -y install gh

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: "software-map"

      - name: Checkout Auto Updater
        uses: actions/checkout@v4
        with:
          repository: "michaelcobb-capablehub/auto-update-software-map"
          fetch-depth: 1
          path: "auto-updater"

      - name: Setup Auto Updater
        shell: bash
        working-directory: ./auto-updater
        run: |
          # Create python3 venv and install requirements:
          python3 -m venv ./venv
          . ./venv/bin/activate
          python3 -m pip install -r requirements.txt

          # Set global env vars:
          echo "OUTPUT_DIR=${{ github.workspace }}" >> $GITHUB_ENV
      - name: Run Auto Updater
        shell: bash
        working-directory: ./auto-updater
        run: |
          . ./venv/bin/activate

          # Create file to contain output from auto-updater (for use in PR body)
          export OUTPUT_FILE="${OUTPUT_DIR}/auto-update.out"
          echo "OUTPUT_FILE=${OUTPUT_FILE}" >> $GITHUB_ENV
          echo "OUTPUT_FILE=${OUTPUT_FILE}"

          #for input_yaml in ${GITHUB_WORKSPACE}/software-map/*.yaml; do
          #  ./main.py ${input_yaml} | tee -a ${OUTPUT_FILE}
          #done
          echo "===================="
          echo "Outputting to file: ${OUTPUT_FILE}"
          ./main.py ${GITHUB_WORKSPACE}/software-map/opensbi.yaml | tee -a ${OUTPUT_FILE}
          echo "===================="
          echo "Contents of output file:"
          cat ${OUTPUT_FILE}
          echo "===================="

      - name: Determine if there are changes
        id: determine_changes
        shell: bash
        working-directory: ./software-map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -n $(git status -s -uall) ]]; then
            echo "Auto updater modified files. A PR will be created..."
            echo "CREATE_PR=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: ${{ steps.determine_changes.outputs.CREATE_PR == 'true' }}
        shell: bash
        working-directory: ./software-map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a unique branch name for this run
          TARGET_BRANCH_NAME="auto-updater/${{github.run_id}}_${{github.run_attempt}}"
          echo "TARGET_BRANCH_NAME=$TARGET_BRANCH_NAME" >> $GITHUB_ENV

          # Set up git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Pushing to branch: '${TARGET_BRANCH_NAME}'..."
          # Create PR branch
          git checkout -b ${TARGET_BRANCH_NAME}
          git add *.yaml
          git commit -m "Auto update software map"
          git push --set-upstream origin ${TARGET_BRANCH_NAME}

      - name: Create PR
        if: ${{ steps.determine_changes.outputs.CREATE_PR == 'true' }}
        shell: bash
        working-directory: ./software-map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: mcobb/auto-update
        run: |
          # Create the PR
          echo "Creating PR to merge branch '${TARGET_BRANCH_NAME}' into '${BASE_BRANCH}'..."
          echo "PR will contain the message body:"
          cat ${OUTPUT_FILE}
          echo ""
          echo ""
          gh pr create \
            --title "Auto update software map" \
            --body-file ${OUTPUT_FILE} \
            --base ${BASE_BRANCH} \
            --head ${TARGET_BRANCH_NAME}
